#!/usr/bin/env bash
# Bash script that display Best School 10 times
# For the 9th iteration display Best School and then Hi on a new line

i=0

while [ $i -le 10 ]
do
	echo "Best School"
	if [ $i -eq 9 ]
	then
	echo "Hi"
	fi
	i=$(( i + 1 ))
done
